version: '3'
services:
  psql:
    build: psql
    volumes:
      - ./psql:/app
      - logvolume01:/var/log
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}
